title: "GitHub - Department of Computer Engineering"
# logo: /assets/img/logo.png
description: "GitHub - Department of Computer Engineering"
# show_downloads: true
# google_analytics:

theme: jekyll-theme-minimal

# Google Analytics Tracking (optional)
ga_tracking: G-10YPVZG432
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
    - jekyll-seo-tag
    - jekyll-readme-index
    - jekyll-sitemap
